### ISSUE TITLE
Dark theme for Firefox Dev Edition

### ISSUE THREAD

**Issue by Aralun** [traxium/tabtree#50] opened 2015-11-12 22:09 UTC
Plop,

Thanks a lot for the add-on. As others, I just saw the Panorama burning notice and switched to Tab Tree. I like it a lot, but my tabs originally had this dark look:

![Screenshot of Firefox Dev Edition default tabs](https://puu.sh/ljhUn/c9b882d523.png)

Tab Tree now makes it look like so:

![Screenshot of Tab Tree tabs](https://puu.sh/ljieP/3143f8d187.png)

All the light is killing my cave dweller eyes! Can we get something darker?

**Comment by Boolean263** [comment] 2015-11-14 03:53
This looks like a duplicate of issue #35. The CSS rules which cause this are fairly straightforward by the look of it, I'll see if I have anything to contribute this weekend.

**Comment by traxium** [comment] 2016-01-11 06:06
If nobody has anything to say I'll close the issue.

**Closed as completed** 2016-01-25 11:27 UTC
Labels: dark theme, done in v1.4.2
