### ISSUE TITLE
Please Add a Feature to Collapse a Tree (or can that already be done?)

### ISSUE THREAD

**Issue by viking2** [traxium/tabtree#130] opened 2016-05-09 20:48 UTC
Please Add a Feature to Collapse a Tree (or can that already be done? How?)

**Comment by mrphang** [comment] 2016-05-24 12:40
I'd like to see this as well
+1

**Comment by karfau** [comment] 2016-06-22 09:22
:+1: 
would also be interesting to know whether this is planned or not

**Comment by jotomo** [comment] 2016-07-19 19:31
Duplicate of #4, with a comment answering the question.

**Closed as completed** 2016-08-18 08:26 UTC
