### ISSUE TITLE
WebExtensions port

### ISSUE THREAD

**Issue by vesatoivonen** [traxium/tabtree#228] opened 2017-09-03 07:28 UTC
Now that tabtree is considered a legacy addon, it should be ported to use the new WebExtensions API for it to be used with Firefox 57 and later versions.

Is this even possible and what kind of work is needed to get rid of legacy status?

**Comment by Fabiensk** [comment] 2017-09-03 19:44
I think it will be quite complicated:

- I read that the WebExtensions does not allow yet hiding the tab bar (there is already a WebExtension displaying vertical tabs, but the original tabs are still there)
- That's a lot of work. Also, WebExtensions looks like… web pages, so it requires emulating the context menus (which will not have a consistent look).

**Comment by polyzen** [comment] 2017-09-03 19:51
Duplicate of #187

**Closed as completed** 2017-09-04 04:29 UTC
