### ISSUE TITLE
Firefox 51. It does not work opening a new tab, the left mouse button or middle mouse button.

### ISSUE THREAD

**Issue by ctiger** [traxium/tabtree#196] opened 2017-01-29 04:01 UTC
Check on Windows 7 and Ubuntu 16.10

**Comment by jayywolff** [comment] 2017-01-29 04:17
This broke for me as well after upgrading to FF 51 on Arch Linux.

**Comment by polyzen** [comment] 2017-01-29 04:24
Probably related to piroor/treestyletab/issues/1246.

**Comment by KorbenOP** [comment] 2017-01-29 10:36
Same here. Win10 x64.

**Comment by Oplkill** [comment] 2017-01-29 12:44
Same Win 10 x64. But working with standart shortcut Ctrl+t

**Comment by nloew** [comment] 2017-01-29 14:26
Same issue with Win 10 x64 @ FF 51.0.1 x32
Also the "+" Button at the bottom is not working, i assume it is the same function

**Comment by allixx** [comment] 2017-01-29 15:51
already fixed in non released (yet?) version https://github.com/traxium/tabtree/issues/170

**Comment by Sporif** [comment] 2017-01-29 16:42
Yep it's already fixed, you can download and then [sign it yourself](https://addons.mozilla.org/en-US/developers/addon/submit/upload-unlisted) or use mine:

https://drive.google.com/open?id=0B_sXN1e_FcQweUZkOTN1NmwzU00

**Comment by ctiger** [comment] 2017-01-29 16:56
Always open a new tab. How to make to open home page? Ctrl-T is working properly. The left and middle button opens a new tab instead of the homepage.

**Comment by jayywolff** [comment] 2017-02-14 14:35
Looks like the fix was applied in the last update and I can confirm it's working again on Arch Linux FF 51.0.1 64-bit. 

Thanks guys :)

**Closed as completed** 2017-08-13 06:05 UTC
