### ISSUE TITLE
[Bug] Tab tree expands horizontally on mouse over and can't be resized

### ISSUE THREAD

**Issue by strigona-worksight** [traxium/tabtree#9] opened 2015-08-19 15:27 UTC
I can no longer grab the edge of the Tab Tree panel when on the Left to resize. Additionally, when hovering over the edge to try and grab it, the Tab tree automatically grows wider.

On the Right side, the edge can be grabbed and resized. So as a work-around, you can swap the tab tree to the right side, resize, then swap back to the left. However with the "auto growth", you'll have to do this somewhat frequently.

**Comment by strigona-worksight** [comment] 2015-08-19 15:30
OK, so after posting this and having swapped it from left to right several times, it appears to have "fixed" itself. It could be an artifact of having just upgraded the addon. I'll let you know if it starts happening again (maybe after restarting the browser??).

**Comment by traxium** [comment] 2015-08-19 18:28
In 1.1.4 I updated css style for toolbar that contains pinned tabs. I think it's the cause of that weird behavior. Thanks for noticing it.

**Comment by strigona-worksight** [comment] 2015-08-24 21:24
For what it's worth, I haven't noticed this issue other than the first time which was right after updating. I'm find with closing this issue.

**Comment by traxium** [comment] 2015-08-24 21:35
Anyway, in 1.1.4 when there were more pinned tabs then the sidebar (on the left) could contain, they stuck out from the sidebar and overlapped a web page. In all other versions excessive pinned tabs were cut off. It's restored in 1.2.0.

**Comment by strigona-worksight** [comment] 2015-08-24 21:42
Ah I see. What happens now? Does it wrap around and add more rows to that toolbar?

**Comment by traxium** [comment] 2015-08-24 21:57
No. It cut them off like it was in the previous versions. Wrapping around and adding more rows (and shrinking it when there are no pinned tabs) would be great but It's put off to a later time.

**Comment by traxium** [comment] 2016-01-11 05:58
If nobody has anything to say I'll close the issue.

**Closed as completed** 2016-01-25 11:23 UTC
Labels: enhanced pinned tab toolbar, done in v1.4.2
