### ISSUE TITLE
[Feature] New tab position

### ISSUE THREAD

**Issue by kirill9000** [traxium/tabtree#19] opened 2015-09-19 04:16 UTC
I'd like to request two crucial features from TST that seem easy to implement:
1) Option to insert new child tabs to the top of the subtree.
2) Option to open new tab (opened via Ctrl+T and other means - e.g. about:addons) as a child of the current tab.
Thank you for your work.

**Comment by wzol** [comment] 2015-09-30 08:13
I'd like to request these features too, they would really help managing my tabs when I open several tabs from one location, and after closing that parent tab, I want to browse each of these opened tabs.

**Comment by traxium** [comment] 2015-11-09 09:18
If a new tab is opened from a pinned tab and browser.tabs.insertRelatedAfterCurrent is set, where should it be positioned: at the bottom or at the top? Does Tree Style Tab have the similar option? I just looked through Tree Style Tab options and couldn't find it.

**Comment by wzol** [comment] 2015-11-09 10:11
I think the problem is that there are too many extensions that change this option. Like mine was changed from the default too, and when I changed it at browser.tabs.insertRelatedAfterCurrent it is now working fine. So at start, I'd just add this same option to the config part of the extension - without any change in the code itself.

**Comment by traxium** [comment] 2015-11-26 00:54
By the way. The add-on respects the "browser.tabs.insertRelatedAfterCurrent" about:config option from version 1.3.8.

**Comment by traxium** [comment] 2015-11-26 05:54
I decided to replace "browser.tabs.insertRelatedAfterCurrent" with "extensions.tabtree.new-child-tab-position" in case the other extensions interfere with this option. So Tab Tree ignores "browser.tabs.insertRelatedAfterCurrent" about:config option from version 1.3.9 (and before 1.3.8).

**Comment by traxium** [comment] 2015-11-27 06:10
I added two context menu options (right-click a tab to access them):
1. Open a new tab as a child (opens a new tab as the last child)
2. Open a new tab as the next sibling (opens a new tab as a sibling next to the current tab)
They will be available in version 1.4.0.

**Comment by traxium** [comment] 2016-01-11 06:01
If nobody has anything to say I'll close the issue.

**Comment by wzol** [comment] 2016-01-11 06:09
For me it is working fine, and thank you!

**Closed as completed** 2016-01-25 11:24 UTC
Labels: should be closed?
