### ISSUE TITLE
Fails to open new TAB

### ISSUE THREAD

**Issue by gregcbrown** [traxium/tabtree#199] opened 2017-02-04 15:31 UTC
Fails to open new TAB by double clicking on empty tab bar, after updating to FireFox 51.0.1.

**Comment by Fabiensk** [comment] 2017-02-04 16:31
Looks like a duplicate of #170 . So I suggest to close this one.
Regarding the title of this bug, I think that "_Fails to open new tab when double clicking on empty tab bar_" would be better (to possibly differenciate it from the other entries in the bug list).

**Comment by floriel** [comment] 2017-02-07 10:01
Since #170 is already closed, it won't help to just close this one as well.
I can confirm that opening a new tab fails and not only when double clicking the empty tab bar, but also when clicking the "+" Button of tab tree.
I'm running Firefox 51.0.1 (64-bit)

**Comment by floriel** [comment] 2017-02-07 10:07
I just realized that this is already fixed (#171) but not jet published on addons.mozilla.org.
Is this a case of "awaiting official signature" and if so, how long will this probably take?

**Comment by GollyJer** [comment] 2017-02-07 20:16
Sweet.  Came to report this and see that it's already been fixed!
Now we wait. 👍

**Comment by traxium** [comment] 2017-02-12 12:51
The fix should already be available on AMO. Thanks to @WyohKnott.

**Comment by floriel** [comment] 2017-02-12 23:03
Yes, I can confirm 1.4.9 is now available in addons.mozilla.org.

**Closed as completed** 2017-08-13 06:05 UTC
