### ISSUE TITLE
Drag and drop tab to other window

### ISSUE THREAD

**Issue by djrobust** [traxium/tabtree#48] opened 2015-11-08 23:35 UTC
When having multiple Firefox windows open, it would be convenient to have the possibility to move a tab from one window to the other, by using drag and drop. (I am unsure whether this is a bug or a feature request, I am running `Ubuntu 15.10 64-bit`, `Firefox 42.0` and `Tab Tree 1.3.7`)

**Comment by robinro** [comment] 2015-11-11 16:23
I also want this :+1:

**Comment by Elemecca** [comment] 2016-01-23 01:10
:+1: this is the only feature I really miss from Tree Style Tab.

**Comment by iegor** [comment] 2016-01-27 11:22
Copying these questions here since, had created duplicate issue #79 

FF 39.0 Linux Gentoo x86_64 multilib
tabstree version: 1.4.2
- What can be done ?
- Could you please point me to the place where you have moving routines,
  maybe I can help with fixing this ?

In issue #6 it was stated

> > I almost figured out how Firefox moves its default tabs between windows and I'll do it when more urgent issues is resolved.

Doubt that would be of much help but as far as I understand the "drop into another window" situation it is some thing like that:
1. Open new child tab of tab under cursor
2. Insert url into newly created tab and "hit go" basically
3. In previous window just close the tab in question.
   NB: I'd took even "fix" version without closing tab in previous window, really.
          Really want to move from "tree style tab" extension and use this one.

Now will close the duplicate issue #79

**Comment by tumpio** [comment] 2016-01-27 11:41
I tried to look some documentation how exactly tabs are moved to new window. All I found from the add-on developer docs was for the new WebExtensions API. 

https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/move

But I found its implementation from Firefox sources:
https://hg.mozilla.org/mozilla-central/file/tip/browser/components/extensions/ext-tabs.js#l581

I hope this helps.

**Comment by tumpio** [comment] 2016-01-27 11:48
I'm also wondering what should happen if the dragged tab is tab tree with child tabs? Should the whole tree get moved to the new window or only the dragged tab?

**Comment by djrobust** [comment] 2016-01-28 05:01
I would argue that moving the whole tree follows the principle of least surprise. It is consistent with the metaphor, when you move a real tree, you also move its branches and leafs.

**Comment by WayneGriswold** [comment] 2016-02-04 21:39
Yes, the desired behavior is to move the whole tree.

**Comment by traxium** [comment] 2016-02-05 12:20
Sorry, I didn't notice your questions earlier, honestly (I saw notification headings and apparently skip all the details).
As of 1.4.3 (this commit 6a24d6ec3d249e3d48a1034255424913edcf636d) the answers are:
- Drag and drop between windows is disabled in [bootstrap.js#1865](https://github.com/traxium/tabtree/blob/6a24d6ec3d249e3d48a1034255424913edcf636d/bootstrap.js?ts=3#L1865-L1883) in `view.canDrop(index, orientation, dataTransfer)`

``` JavaScript
if (draggedTab.parentNode == g.tabContainer) { // if it's the same window
  ...
  // As you can see there is no eslse
  ...
}
```
- Drag begins at [#1142](https://github.com/traxium/tabtree/blob/6a24d6ec3d249e3d48a1034255424913edcf636d/bootstrap.js?ts=3#L1442). But I think there's no need to change anything here:

``` JavaScript
treechildren.addEventListener('dragstart', function(event) { // if the event was attached to 'tree' then the popup would be shown while you scrolling
```
- Drop ends at [#1894](https://github.com/traxium/tabtree/blob/6a24d6ec3d249e3d48a1034255424913edcf636d/bootstrap.js?ts=3#L1894) in `view.drop(row, orientation, dataTransfer)`:

``` JavaScript
drop: function(row, orientation, dataTransfer) {
```

And there are a set of event listeners for moving pinned tabs, but there is almost nothing Firefox specific. I used [this guide](https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API):

``` JavaScript
toolbar.addEventListener('dragstart', function(event) {}, false);
toolbar.addEventListener('dragover', (event) => {}, false);
toolbar.addEventListener('dragleave', function f(event) {}, false);
toolbar.addEventListener('drop', function f(event) {}, false);
```

I was going to use the implementation from [tabbrowser.xml#5763](http://mxr.mozilla.org/mozilla-aurora/source/browser/base/content/tabbrowser.xml#5763) but the implementation from [your link](https://hg.mozilla.org/mozilla-central/file/tip/browser/components/extensions/ext-tabs.js#l581) will probably be better suited. But as it seems `swapBrowsersAndCloseOther(newTab, tab);` does the magic in both cases.

Anyway I'm going to do this issue next.

**Comment by traxium** [comment] 2016-02-12 12:52
It's ready. It'll be available in version 1.4.4.

**Comment by djrobust** [comment] 2016-02-14 22:18
Thank you very much!

**Comment by traxium** [comment] 2016-03-15 09:20
The issue is resolved. I'll close the issue.

**Closed as completed by traxium** 2016-03-15 09:20 UTC
Labels: drag and drop between windows
